# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Недвижимость в Москве
#email: your-email@domain.com
description: Новостройка от официального застройщика или вторичка. 
  Когда покупать, у кого и за сколько. На что обратить внимание при приобретении квартиры.
baseurl: "/irusslan.github.io" # the subpath of your site, e.g. /blog
url: "https://" # the base hostname & protocol for your site
#twitter_username: Taffyer 
#github_username:  wild-flame 
permalink: /:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
plugins: 
 - jekyll-sitemap
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname: ot-rf

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
